(load-module "stdlib/list.lisp")
(load-module "examples/factorial.lisp")

(print-ln "Hi! I'm a stupid calculator. I can either multiply or add two numbers or calculate a factorial.")
(print-ln "Please, type either '+' or '*', and then two numbers, or 'factorial' and then one number")

(define print' (&rest args)
  (map print args))

(define print-ln' (&rest args)
  (map print args)
  (print-ln ""))

(define get-int () (str-to-int (get-line)))
(define get-float () (str-to-float (get-line)))
(defvar print-number (bind print-ln' "Your number is "))

(let ((input (get-line)))
  (if (= input "*")
    (let ((n1 (get-float)) (n2 (get-int)) (mult (* n1 n2)))
      (print-number mult)
    )
    (if (= input "+")
      (let ((n1 (get-float)) (n2 (get-int)) (sum (+ n1 n2)))
        (print-number sum)
      )
      (if (= input "factorial")
        (let ((n (get-int)) (f (factorial n)))
          (print-number f)
        )
        (print-ln "Error: you entered neither + or *. Go to hell, bitch.")
      )
    )
  )
)
